version: '3.9'

services:
  db:
    container_name: "product-service-database"
    image:  postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    container_name: 'product-service-app'
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8443:8443"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=8888
    ports:
      - "8888:8888"
